# Welcome To NumPy

In [1]:
import numpy as np

In [2]:
myarr = np.array([12,34,45,67], np.int64)

In [3]:
myarr

array([12, 34, 45, 67], dtype=int64)

In [4]:
myarr[2]

45

In [5]:
myarr1 = np.array([[23,45,76,89]], np.int32)

In [6]:
myarr1

array([[23, 45, 76, 89]])

In [7]:
myarr1[0]

array([23, 45, 76, 89])

In [8]:
myarr1[0,2]

76

In [9]:
myarr.shape

(4,)

In [10]:
myarr1.shape

(1, 4)

In [11]:
myarr1.dtype

dtype('int32')

In [12]:
myarr.dtype

dtype('int64')

In [13]:
myarr[0] = 100

In [14]:
myarr

array([100,  34,  45,  67], dtype=int64)

In [15]:
myarr1[0,0] =100

In [16]:
myarr1

array([[100,  45,  76,  89]])

***Array creation: Conversion from other Python structure***

In [17]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [18]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
listarray.dtype

dtype('int32')

In [20]:
listarray.shape

(3, 3)

In [21]:
listarray.size

9

***Intrinsic numpy array creation object***

In [22]:
zeros = np.zeros((2,3))

In [23]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
zeros.shape

(2, 3)

In [25]:
zeros.dtype

dtype('float64')

In [26]:
rng = np.arange(19)

In [27]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [28]:
lspace = np.linspace(1,18,10)

In [29]:
lspace

array([ 1.        ,  2.88888889,  4.77777778,  6.66666667,  8.55555556,
       10.44444444, 12.33333333, 14.22222222, 16.11111111, 18.        ])

In [30]:
emp = np.empty((2,3))

In [31]:
emp

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
emp_like = np.empty_like(lspace)

In [33]:
emp_like

array([ 1.        ,  2.88888889,  4.77777778,  6.66666667,  8.55555556,
       10.44444444, 12.33333333, 14.22222222, 16.11111111, 18.        ])

In [34]:
ide = np.identity(45)

In [35]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [36]:
ide.shape

(45, 45)

In [37]:
arr = np.arange(99)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [39]:
arr = arr.reshape(3,33)

In [40]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [41]:
arr = arr.ravel()

In [42]:
arr.shape

(99,)

In [43]:
x = [[1,2,3], [4,5,6], [7,8,9], [10,11,12]]

In [44]:
ar = np.array(x)

In [45]:
ar

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [46]:
ar.sum(axis=0)

array([22, 26, 30])

In [47]:
ar.sum(axis=1)

array([ 6, 15, 24, 33])

In [48]:
ar.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [49]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9
10
11
12


In [50]:
ar.ndim

2

In [51]:
ar.size

12

In [52]:
ar.nbytes

48

In [53]:
oned = np.array([12,34,344,56,78,90])

In [54]:
oned

array([ 12,  34, 344,  56,  78,  90])

In [55]:
oned.argmax()

2

In [56]:
oned.argmin()

0

In [57]:
oned.argsort()

array([0, 1, 3, 4, 5, 2], dtype=int64)

In [58]:
ar

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [59]:
ar.argmax()

11

In [60]:
ar.argmin()

0

In [61]:
ar.argmax(axis=0)

array([3, 3, 3], dtype=int64)

In [62]:
ar.argmax(axis=1)

array([2, 2, 2, 2], dtype=int64)

In [63]:
ar.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [64]:
ar.argmin(axis=1)

array([0, 0, 0, 0], dtype=int64)

In [65]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [66]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]], dtype=int64)

In [67]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [68]:
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [69]:
ar.shape

(4, 3)

In [70]:
ar.reshape((2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [71]:
ar.reshape((6,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [72]:
ar

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [73]:
ar1 = np.array([[ 13,14,15],
       [ 16,17,18],
       [ 19,20,21],
       [22,23,24]])

In [74]:
ar1

array([[13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [75]:
ar + ar1

array([[14, 16, 18],
       [20, 22, 24],
       [26, 28, 30],
       [32, 34, 36]])

In [76]:
ar1 - ar

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

In [77]:
ar-ar1

array([[-12, -12, -12],
       [-12, -12, -12],
       [-12, -12, -12],
       [-12, -12, -12]])

In [78]:
ar*ar1

array([[ 13,  28,  45],
       [ 64,  85, 108],
       [133, 160, 189],
       [220, 253, 288]])

In [79]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162]])

In [80]:
np.sqrt(ar1)

array([[3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069],
       [4.35889894, 4.47213595, 4.58257569],
       [4.69041576, 4.79583152, 4.89897949]])

In [81]:
ar1.sum()

222

In [82]:
ar1.max()

24

In [83]:
ar1.min()

13

In [84]:
ar

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [85]:
np.where(ar>5)

(array([1, 2, 2, 2, 3, 3, 3], dtype=int64),
 array([2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [86]:
np.where(ar<5)

(array([0, 0, 0, 1], dtype=int64), array([0, 1, 2, 0], dtype=int64))

In [87]:
np.count_nonzero(ar)

12

In [88]:
import sys

In [89]:
py_ar = [23,67,54,97,87]

In [90]:
np_ar = np.array(py_ar)

In [91]:
py_ar

[23, 67, 54, 97, 87]

In [92]:
np_ar

array([23, 67, 54, 97, 87])

In [93]:
sys.getsizeof(1) * len(py_ar)

140

In [94]:
np_ar.itemsize * np_ar.size

20

# Creating NumPy Array(One Dimensional)

In [95]:
a = [1,2,3,4,5,6,7]

In [96]:
myarr = np.array(a)

In [97]:
myarr

array([1, 2, 3, 4, 5, 6, 7])

In [98]:
myarr = np.array([12,23,45,6,7,78])

In [99]:
myarr

array([12, 23, 45,  6,  7, 78])

In [100]:
import numpy as np
a = []
n = int(input("Enter size of an array : "))
for i in range(n):
    val = int(input("Enter number : "))
    a.append(val)
    
myarray = np.array(a)
myarray

Enter size of an array : 4
Enter number : 1
Enter number : 2
Enter number : 3
Enter number : 4


array([1, 2, 3, 4])

# Creating NumPy Array(Two Dimensional)

In [101]:
x = [[1,2,3], [4,5,6], [7,8,9]]
arr = np.array(x)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [103]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
print("Dimension of array is : ",arr.ndim)

Dimension of array is :  2


In [105]:
print("Shape of array : ",arr.shape)

Shape of array :  (3, 3)


# NumPy Function

In [106]:
import numpy as np

In [107]:
arr = np.zeros(7)

In [108]:
arr

array([0., 0., 0., 0., 0., 0., 0.])

In [109]:
arr1 = np.zeros((6,7))

In [110]:
arr1

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [111]:
arr = np.ones(6)

In [112]:
arr

array([1., 1., 1., 1., 1., 1.])

In [113]:
arr = np.ones((4,5))

In [114]:
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [115]:
arr = np.eye(8)

In [116]:
arr

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [117]:
arr = np.eye(7,8)

In [118]:
arr

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.]])

In [119]:
arr = np.diag([2,3,4,5,6,7,8])

In [120]:
arr

array([[2, 0, 0, 0, 0, 0, 0],
       [0, 3, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 8]])

In [121]:
np.diag(arr)

array([2, 3, 4, 5, 6, 7, 8])

In [122]:
import numpy as np
arr = np.random.randint(1,10,3)
arr

array([6, 7, 7])

In [123]:
arr = np.random.rand(5)
arr

array([0.94169902, 0.44024131, 0.10977074, 0.89353425, 0.63623802])

In [124]:
arr = np.random.rand(2,3)
arr

array([[0.40496905, 0.787353  , 0.40604751],
       [0.1478239 , 0.4708392 , 0.07536193]])

In [125]:
arr = np.random.randn(4)
arr

array([-0.86020143,  1.50460853, -0.61805425, -1.77085444])

# Indexing & Slicing of Numpy 1D Array

In [126]:
a = []
n = int(input("Enter your array size : "))
for i in range(n):
    val = int(input("Enter value : "))
    a.append(val)
    
arr = np.array(a)
for i in range(arr.size):
    print(arr[i])
    
sum = 0
for i in range(arr.size):
    sum = sum + arr[i]
    
print(sum)    
    

Enter your array size : 5
Enter value : 12
Enter value : 23
Enter value : 34
Enter value : 45
Enter value : 56
12
23
34
45
56
170


In [127]:
a = []
n = int(input("Enter your array size : "))
for i in range(n):
    val = int(input("Enter value : "))
    a.append(val)
    
arr = np.array(a)
for i in range(arr.size):
    print(arr[i])
    
arr1 = arr[2:6]
print(arr1)

Enter your array size : 7
Enter value : 11
Enter value : 22
Enter value : 33
Enter value : 44
Enter value : 55
Enter value : 66
Enter value : 77
11
22
33
44
55
66
77
[33 44 55 66]


# Reshaping Array

In [128]:
arr = np.random.randint(1,20,12)

In [129]:
arr

array([17,  1,  9, 13, 14,  8, 19,  7,  5, 15,  8, 18])

In [130]:
arr.shape

(12,)

In [131]:
arr.reshape(2,6)

array([[17,  1,  9, 13, 14,  8],
       [19,  7,  5, 15,  8, 18]])

In [132]:
arr.reshape(3,4)

array([[17,  1,  9, 13],
       [14,  8, 19,  7],
       [ 5, 15,  8, 18]])

In [133]:
arr.reshape(6,2)

array([[17,  1],
       [ 9, 13],
       [14,  8],
       [19,  7],
       [ 5, 15],
       [ 8, 18]])

In [134]:
arr.reshape(4,3)

array([[17,  1,  9],
       [13, 14,  8],
       [19,  7,  5],
       [15,  8, 18]])

In [135]:
arr.reshape(12)

array([17,  1,  9, 13, 14,  8, 19,  7,  5, 15,  8, 18])

In [136]:
arr.reshape(2,2,3)

array([[[17,  1,  9],
        [13, 14,  8]],

       [[19,  7,  5],
        [15,  8, 18]]])

In [137]:
arr.reshape(3,2,2)

array([[[17,  1],
        [ 9, 13]],

       [[14,  8],
        [19,  7]],

       [[ 5, 15],
        [ 8, 18]]])

In [138]:
arr.ndim

1

In [139]:
a = arr.reshape(3,2,2)

In [140]:
a

array([[[17,  1],
        [ 9, 13]],

       [[14,  8],
        [19,  7]],

       [[ 5, 15],
        [ 8, 18]]])

In [141]:
a.ndim

3

In [142]:
arr.reshape(3,-1)

array([[17,  1,  9, 13],
       [14,  8, 19,  7],
       [ 5, 15,  8, 18]])

In [143]:
arr.reshape(4,-1)

array([[17,  1,  9],
       [13, 14,  8],
       [19,  7,  5],
       [15,  8, 18]])

In [144]:
arr.reshape(-1,6)

array([[17,  1,  9, 13, 14,  8],
       [19,  7,  5, 15,  8, 18]])

# Seed Function in Numpy

In [145]:
np.random.seed(12)
arr = np.random.randint(1,100,10)
arr


array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])

In [146]:
arr

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])

In [147]:
arr

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])

In [148]:
arr.size

10

# Creating User Defined 2D Array

In [149]:
import numpy as np
matrix = []
row = int(input("Enter Number of Row : "))
col = int(input("Enter Number of Col : "))
for i in range(row):
    a=[]
    for j in range(col):
        val = int(input("Enter number : "))
        a.append(val)
    matrix.append(a)
arr = np.array(matrix)
for i in range(row):
    for j in range(col):
        print(arr[i][j],end=" ")
    print()    

Enter Number of Row : 4
Enter Number of Col : 4
Enter number : 1
Enter number : 2
Enter number : 3
Enter number : 4
Enter number : 5
Enter number : 6
Enter number : 7
Enter number : 8
Enter number : 9
Enter number : 10
Enter number : 11
Enter number : 12
Enter number : 13
Enter number : 14
Enter number : 15
Enter number : 16
1 2 3 4 
5 6 7 8 
9 10 11 12 
13 14 15 16 


In [150]:
print(type(arr))

<class 'numpy.ndarray'>


# Slicing of 2D Array

In [151]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [152]:
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [153]:
a[:2,1:3]

array([[2, 3],
       [5, 6]])

In [154]:
import numpy as np
np.random.seed(111)
a = np.random.randint(1,500,30).reshape(6,5)
a

array([[341, 365, 469, 213,  87],
       [276, 170, 323, 119, 467],
       [297, 456, 442,   8, 269],
       [267, 450, 369, 217, 285],
       [271, 419,  22,  55, 201],
       [ 38, 461, 231, 187, 269]])

In [155]:
a[2:,2:]

array([[442,   8, 269],
       [369, 217, 285],
       [ 22,  55, 201],
       [231, 187, 269]])

In [156]:
a[2:3,2:3]

array([[442]])

# View vs Copy

In [157]:
#View
import numpy as np
a = np.array([10,20,30,40,50,60,70])
slicing = a[2:5]
slicing[:]=0
a

array([10, 20,  0,  0,  0, 60, 70])

In [158]:
#Copy
import numpy as np
a = np.array([10,20,30,40,50,60,70])
slicing = a[2:5].copy()
slicing[:]=0
a

array([10, 20, 30, 40, 50, 60, 70])

# Conditional Selection

In [159]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [160]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [161]:
a%2 == 0

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False])

In [162]:
b=[a%2==1]

In [163]:
b

[array([ True, False,  True, False,  True, False,  True, False,  True,
        False,  True, False,  True, False,  True])]

In [164]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

# Operations on array

In [165]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [166]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [167]:
a**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225], dtype=int32)

In [168]:
a+2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [169]:
arr1 = np.arange(1,5)
arr2 = np.arange(5,9)
arr1+arr2

array([ 6,  8, 10, 12])

In [170]:
import numpy as np
x = np.array([1,2,3,4]).reshape(2,2)
x

array([[1, 2],
       [3, 4]])

In [171]:
y = np.array([5,6,7,8]).reshape(2,2)
y

array([[5, 6],
       [7, 8]])

In [172]:
x+y

array([[ 6,  8],
       [10, 12]])

In [173]:
x-y

array([[-4, -4],
       [-4, -4]])

In [174]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [175]:
x.dot(y)

array([[19, 22],
       [43, 50]])

In [176]:
x*y

array([[ 5, 12],
       [21, 32]])

In [177]:
x**y

array([[    1,    64],
       [ 2187, 65536]], dtype=int32)

# Numpy Some More Function

In [178]:
arr = np.array([78,34,67,43,99,44,10,38,32])
arr

array([78, 34, 67, 43, 99, 44, 10, 38, 32])

In [179]:
np.min(arr)

10

In [180]:
np.max(arr)

99

In [181]:
np.argmin(arr)

6

In [182]:
np.argmax(arr)

4

In [183]:
np.sqrt(arr)

array([8.83176087, 5.83095189, 8.18535277, 6.55743852, 9.94987437,
       6.63324958, 3.16227766, 6.164414  , 5.65685425])

In [184]:
np.sin(arr)

array([ 0.51397846,  0.52908269, -0.85551998, -0.83177474, -0.99920683,
        0.01770193, -0.54402111,  0.29636858,  0.55142668])

In [185]:
np.cos(arr)

array([-0.85780309, -0.84857027, -0.5177698 ,  0.5551133 ,  0.03982088,
        0.99984331, -0.83907153,  0.95507364,  0.83422336])

In [186]:
np.linspace(1,6,5)

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [187]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [188]:
np.random.seed(122)

In [189]:
matrix = np.random.randint(1,21,9).reshape(3,3)
matrix

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [190]:
np.sum(matrix)

116

In [191]:
np.min(matrix)

3

In [192]:
np.max(matrix)

17

In [193]:
np.min(matrix,axis=1)

array([11, 13,  3])

In [194]:
np.max(matrix,axis=0)

array([17, 16, 16])

In [195]:
np.sum(matrix,axis=1)

array([40, 46, 30])

In [196]:
np.sum(matrix,axis=0)

array([36, 40, 40])

In [197]:
np.cumsum(matrix)

array([ 16,  27,  40,  57,  70,  86,  89, 105, 116], dtype=int32)

In [198]:
np.cumsum(matrix,axis=0)

array([[16, 11, 13],
       [33, 24, 29],
       [36, 40, 40]], dtype=int32)

In [199]:
np.cumsum(matrix,axis=1)

array([[16, 27, 40],
       [17, 30, 46],
       [ 3, 19, 30]], dtype=int32)

In [200]:
matrix

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [201]:
np.random.shuffle(matrix)
matrix

array([[16, 11, 13],
       [ 3, 16, 11],
       [17, 13, 16]])

In [202]:
np.unique(matrix)

array([ 3, 11, 13, 16, 17])

In [203]:
np.unique(matrix).size

5

In [204]:
np.unique(matrix,return_index=True,return_counts=True)

(array([ 3, 11, 13, 16, 17]),
 array([3, 1, 2, 0, 6], dtype=int64),
 array([1, 2, 2, 3, 1], dtype=int64))

# Numpy Stacking

In [205]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

In [206]:
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [207]:
np.vstack((arr1,arr2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [208]:
np.random.seed(122)
arr1=np.random.randint(1,21,9).reshape(3,3)
arr2=np.random.randint(21,31,9).reshape(3,3)

In [209]:
arr1

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [210]:
arr2

array([[26, 30, 27],
       [24, 25, 24],
       [24, 21, 25]])

In [211]:
np.hstack((arr1,arr2))

array([[16, 11, 13, 26, 30, 27],
       [17, 13, 16, 24, 25, 24],
       [ 3, 16, 11, 24, 21, 25]])

In [212]:
np.vstack((arr1,arr2))

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11],
       [26, 30, 27],
       [24, 25, 24],
       [24, 21, 25]])

# Numpy Exercise

In [213]:
#1.write statement to import numpy...??
import numpy as np

In [214]:
#2. create an array using numpy....??
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [215]:
#3.create an array of 10 random integers....??
arr = np.random.randint(1,100,10)
arr

array([16, 82, 61, 76, 64, 43,  7, 49, 86, 41])

In [216]:
#4.create an array of elements from 10-20....??
arr = np.arange(10,21)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [217]:
#5.create an array which contains value 5,10 times...??
arr = np.ones(10)*5
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [218]:
#6.create a one dimentional array and convert that into 3*3 matrix....??
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [219]:
#7.create an array and then convert all the even numbers with 0...??
arr=np.arange(1,11)
arr[arr%2==0]=0
arr

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

In [220]:
#8.create a 2D array of size 3*3 but all the elements should be between 0 and 1...??
arr=np.random.rand(9).reshape(3,3)
arr

array([[0.67515235, 0.41526399, 0.37040662],
       [0.72482967, 0.34418396, 0.52770975],
       [0.87016427, 0.77298345, 0.9194153 ]])

In [221]:
#9. Perform the following slicing...

# Input:                     Output:

# 1  2  3  4                 6  7
# 5  6  7  8                10  11
# 9 10 11 12                14  15
# 13 14 15 16

arr1 = np.arange(1,17).reshape(4,4)
arr2 = arr1[1:,1:3]
arr2

array([[ 6,  7],
       [10, 11],
       [14, 15]])

In [222]:
#10.concatenate 2D array horizontally and vertically
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(10,19).reshape(3,3)
np.hstack((arr1,arr2))

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [223]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

# Numpy vs List

In [224]:
%timeit [i**2 for i in range(1,11)]

7.8 µs ± 222 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [225]:
import numpy as np
%timeit np.arange(1,11)**2

3.13 µs ± 31.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Numpy Searching Arrays

In [226]:
arr = np.array([10,20,40,37,78,40,34,78,40])
x = np.where(arr==40)
x

(array([2, 5, 8], dtype=int64),)

In [227]:
a = np.array([1,2,3,4,5,6,7,8,9])
res = np.where(a%2==0)
res

(array([1, 3, 5, 7], dtype=int64),)

In [228]:
a = np.array([2,5,8,11,14,17,20])
x = np.searchsorted(a,18)
x

6

In [229]:
a = np.array([2,5,8,11,14,17,20])
x = np.searchsorted(a,12,side="right")
x

4